version: "3.8"

services:
  web:
    build: .
    container_name: snappy-duck-worker
    ports:
      - "8000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    
