services:
  - type: web
    name: snappy-duck-worker
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
    disk:
      name: docker-socket
      mountPath: /var/run/docker.sock
      sizeGB: 1